name: OctoBot-Trading-Cron
on:
  schedule:
    - cron: '0 5 * * *' # every day at 5am

jobs:
  real-exchange-tests:
    name: ubuntu-latest - Python 3.8 - ${{ matrix.exchange }} - real exchange tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        exchange: [ ascendex, binance, bitfinex, bithumb, bitstamp, bittrex, bybit, coinbasepro, crex24, ftx, gateio, hollaex, hitbtc, huobi, huobipro, kraken, kucoin, okcoin, okx, poloniex, upbit, wavesexchange, bitget ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
        architecture: 'x64'

    - name: Install dependencies
      run: pip install --prefer-binary -r dev_requirements.txt -r requirements.txt

    - name: Pytests
      run: pytest -rw tests_additional/real_exchanges/test_${{ matrix.exchange }}.py

  notify:
    if: ${{ failure() }}
    needs:
      - real-exchange-tests
    uses: Drakkar-Software/.github/.github/workflows/failure_notify_workflow.yml@master
    secrets:
      DISCORD_GITHUB_WEBHOOK: ${{ secrets.DISCORD_GITHUB_WEBHOOK }}
