name: OctoBot-Trading-Cron
on:
  schedule:
    - cron: '0 5 * * *' # every day at 5am

jobs:
  tests:
    name: ubuntu-latest - Python 3.8 - ${{ matrix.type }} - tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [ sources, cython ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
        architecture: 'x64'

    - name: Install dependencies
      run: pip install --prefer-binary -r dev_requirements.txt -r requirements.txt

    - name: Compile project
      if: matrix.type == 'cython'
      env:
        CYTHON_IGNORE: true
      run: |
        python setup.py build_ext --inplace
        python setup.py install

    - name: Pytests
      run: pytest --cov=. --cov-config=.coveragerc --durations=0 -rw tests_additional

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs:
      - tests
    if: ${{ failure() }}

    steps:
      - name: Notify discord
        uses: sarisia/actions-status-discord@v1
        with:
          status: Failure
          webhook: ${{ secrets.DISCORD_GITHUB_WEBHOOK }}
